name: Flags quiz
on:
  push:
    branches:
      - master

jobs:
  quality-assurance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dart
        uses: cedx/setup-dart@v2

      - name: Install flutter
        uses: subosito/flutter-action@v1
        with:
          channel: dev

      - name: Install upcode
        run: |
          u
          echo "~/.pub-cache/bin" >> $GITHUB_PATH

      - name: Setup project
        run: flutter pub get

      - name: Check code format
        run: upcode flutter:format

      - name: Check code
        run: upcode flutter:analyze




